### PR TITLE
Add enable-updates config option

### PR DESCRIPTION
**Pull request by LunaWasFlaggedAgain**

### CODE REVIEW

**Review by allinkdev — APPROVED** [review]

**Comment by Telesphoreo** [comment]
Sorry, I didn't know you wanted to contribute this to Plex itself. Personally I'd rather have it be a hidden option by setting the repository to blank

**Comment by allinkdev** [comment]
> Sorry, I didn't know you wanted to contribute this to Plex itself. Personally I'd rather have it be a hidden option by setting the repository to blank

To be honest, I think it'd be better off and easier to use as a seperate configuration value. Maybe so you don't have to remember the repo URL if you want to re-enable them.

**Comment by Telesphoreo** [comment]
> > Sorry, I didn't know you wanted to contribute this to Plex itself. Personally I'd rather have it be a hidden option by setting the repository to blank
> 
> To be honest, I think it'd be better off and easier to use as a seperate configuration value. Maybe so you don't have to remember the repo URL if you want to re-enable them.

I don't want to necessarily encourage disabling updates

**Comment by Telesphoreo** [comment]
I'm going to close this because this isn't necessarily how I want it done and there wasn't an approved issue for this in the first place

**Pull request closed without merging**
